### ISSUE TITLE
Meteor 1.2.0.2 - Cannot read property 'ToyKit' of undefined

### ISSUE THREAD

**Issue by ghost** [MeteorToys/ToyKit#1]
Packages:

```
msavin:jetsetter                 1.3.1  Visual Get/Set Tool for Sessions
msavin:mongol                    1.4.3  The insanely handy development package for Meteor.
```

Stack trace:

```
I20151009-14:27:25.535(-6)? Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
I20151009-14:27:25.535(-6)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
I20151009-14:27:25.535(-6)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
I20151009-14:27:25.535(-6)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151009-14:27:25.536(-6)?     at livedata_server.js:708:19
I20151009-14:27:25.537(-6)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151009-14:27:25.537(-6)?     at livedata_server.js:706:40
I20151009-14:27:25.537(-6)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151009-14:27:25.537(-6)?     at livedata_server.js:704:46
I20151009-14:27:25.538(-6)?     at tryCallTwo (/Users/chris/.meteor/packages/promise/.0.5.0.xnq76f++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151009-14:27:25.538(-6)?     at doResolve (/Users/chris/.meteor/packages/promise/.0.5.0.xnq76f++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151009-14:27:25.538(-6)?     at new Promise (/Users/chris/.meteor/packages/promise/.0.5.0.xnq76f++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151009-14:27:25.539(-6)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20151009-14:27:25.539(-6)?     at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:52:1
I20151009-14:27:25.539(-6)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151009-14:27:25.539(-6)?     at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:51:1)
I20151009-14:27:25.540(-6)?     at livedata_server.js:548:43
```

**Comment by msavin** [comment]
Can you please send a list of packages?

**Comment by ghost** [comment]
Sure. Here you go:

accounts-password                1.1.3  Password support for accounts
aldeed:collection2               2.5.0  Automatic validation of insert and update operations on the client and server.
aslagle:reactive-table           0.8.16  A reactive table designed for Meteor
babrahams:temple                 0.3.3  Developer tool that provides visual information about templates
blaze-html-templates             1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
browser-policy                   1.0.5  Configure security policies enforced by the browser
ccuilla:add-to-calendar-buttons  0.0.1+ Easily add a "add to calendar" button to your websites. This JavaScript library supports Google Calendar, iCal, Outlook a...
ccuilla:mixpanel                 0.0.1+
cfs:access-point                 0.1.49  CollectionFS, add ddp and http accesspoint capability
cfs:filesystem                   0.1.2  Filesystem storage adapter for CollectionFS
cfs:graphicsmagick               0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:s3                           0.1.3  Amazon Web Services S3 storage adapter for CollectionFS
cfs:standard-packages            0.5.9  Filesystem for Meteor, collectionFS
cfs:ui                           0.1.3  CollectionFS, provides UI helpers
chart:chart                      1.0.1-beta.4  Chart.js (official) - Responsive, simple, clean and interactive charts using HTML5 <canvas>
check                            1.0.6  Check whether a value matches a pattern
constellation:autopublish        0.3.4  Autopublish toggle plugin for Constellation
constellation:console            1.2.1  An extensible development console for Meteor
constellation:position           0.3.2  Positioning plugin for Constellation
constellation:session            0.3.2  Session variable editor plugin for Constellation
constellation:subscriptions      0.3.1  Subscriptions plugin for Constellation
constellation:tiny               0.3.1  Minification plugin for Constellation
copleykj:stripe-sync             2.0.5  Sync wrapper for stripe-node
dburles:collection-helpers       1.0.3  Transform your collections with helpers that you define
ecmascript                       0.1.5  Compiler plugin that supports ES2015+ in all .js files
ejson                            1.0.7  Extended and Extensible JSON library
email                            1.0.7  Send email messages
fastclick                        1.0.7  Faster touch events on mobile
froatsnook:request               2.64.0  A Simplified HTTP client which supports retrieving binary data
gadicohen:reactive-window        1.0.6  Reactive functions for window properties; width, scroll, etc
gilbertwat:moment-recur          1.0.4  Depends on official momentjs recurring date plugin for momentjs.
ian:accounts-ui-bootstrap-3      1.2.81  Bootstrap-styled accounts-ui with multi-language support.
infinitedg:winston               0.7.3  A multi-transport async logging library for node.js. "CHILL WINSTON! ... I put it in the logs."
iron:router                      1.0.12  Routing specifically designed for Meteor
jamiter:pluralize                1.0.2  Pluralize or singularize any word based on a count
jplack:bootstrap-timepicker      0.2.1  Bootstrap 3 timepicker for Meteor.
jquery                           1.11.4  Manipulate the DOM using CSS selectors
kadira:debug                     2.2.4  Full Stack Debugging Solution for Meteor
lai:ddp-inspector                1.1.7  See all DDP activity in the client-side and full-text search them.
lepozepo:publish-with-relations  1.2.4  Publish associated collections at once.
less                             2.5.0_3  Leaner CSS language
logging                          1.0.8  Logging facility.
matb33:collection-hooks          0.8.1  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-base                      1.0.1  Packages that every Meteor app needs
meteorhacks:aggregate            1.3.0  Proper MongoDB aggregations support for Meteor
meteorhacks:fast-render          2.10.0  Render your app before the DDP connection even comes alive - magic?
meteorhacks:kadira               2.23.6  Performance Monitoring for Meteor
meteorhacks:kadira-profiler      1.2.1  CPU Profiler for Meteor (used with Kadira)
meteorhacks:ssr                  2.1.2  Server Side Rendering for Meteor with Blaze
mobile-experience                1.0.1  Packages for a great mobile user experience
momentjs:moment                  2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                            1.1.2  Adaptor for using MongoDB and Minimongo over DDP
msavin:jetsetter                 1.3.1  Visual Get/Set Tool for Sessions
msavin:mongol                    1.4.3  The insanely handy development package for Meteor.
okgrow:iron-router-autoscroll    0.0.11  Deprecated - pulls in okgrow:router-autoscroll
percolate:synced-cron            1.3.0  Allows you to define and run scheduled jobs across multiple servers.
raix:handlebar-helpers           0.2.5  Handlebar helpers
rajit:bootstrap3-datepicker      1.4.1  Meteor packaging of eternicode/bootstrap-datepicker for Bootstrap 3
random                           1.0.4  Random number generator and utilities
reactive-dict                    1.1.2  Reactive dictionary
reactive-var                     1.0.6  Reactive variable
reload                           1.1.4  Reload the page while preserving application state.
sacha:spin                       2.3.1  Simple spinner package for Meteor
session                          1.1.1  Session variable
spacebars                        1.0.7  Handlebars-like template language for Meteor
standard-minifiers               1.0.1  Standard minifiers used with Meteor apps by default.
tracker                          1.0.9  Dependency tracker to allow reactive callbacks
tsega:bootstrap3-datetimepicker  3.1.3_3\* Bootstrap 3 DateTime picker from @Eonasdan, packaged for Meteor.js
twbs:bootstrap                   3.3.5  The most popular front-end framework for developing responsive, mobile first projects on the web.
underscore                       1.0.4  Collection of small helpers: _.map, _.each, ...
yasaricli:lightbox               0.0.3_2  Simple to render lightbox meteor templates.

**Comment by jackkav** [comment]
+1

**Comment by sylido** [comment]
+1

**Comment by cyounghusband** [comment]
+1

I have fewer packages -- i'm in the process of building an app specific version for my main application:

accounts-password                   1.1.3  Password support for accounts
accounts-ui                         1.1.6  Simple templates to add login widg...
aldeed:collection2                  2.5.0  Automatic validation of insert and...
anonyfox:mmenu                      0.0.1  Wrapper for http://mmenu.frebsite.nl/
autopublish                         1.0.4  (For prototyping only) Publish the...
blaze-html-templates                1.0.1  Compile HTML templates into reacti...
cfs:filesystem                      0.1.2  Filesystem storage adapter for Col...
cfs:gridfs                          0.0.33  GridFS storage adapter for Collec...
cfs:standard-packages               0.5.9  Filesystem for Meteor, collectionFS
cordova:com.mbppower.camerapreview  file://./private/plugins/CordovaCameraPre...
ecmascript                          0.1.5  Compiler plugin that supports ES20...
es5-shim                            4.1.13  Shims and polyfills to improve EC...
fortawesome:fontawesome             4.4.0  Font Awesome (official): 500+ scal...
fourseven:scss                      3.3.3_3  Style with attitude. Sass and SC...
insecure                            1.0.4  (For prototyping only) Allow all d...
iron:router                         1.0.12  Routing specifically designed for...
jquery                              1.11.4  Manipulate the DOM using CSS sele...
meteor-base                         1.0.1  Packages that every Meteor app needs
mobile-experience                   1.0.1  Packages for a great mobile user e...
mongo                               1.1.2  Adaptor for using MongoDB and Mini...
msavin:mongol                       1.4.3  The insanely handy development pac...
session                             1.1.1  Session variable
standard-minifiers                  1.0.1  Standard minifiers used with Meteo...
steeve:single-page-login            0.5.1  A meteor package for a Bootstrap 3...
tracker                             1.0.9  Dependency tracker to allow reacti...
twbs:bootstrap                      3.3.5  The most popular front-end framewo...

**Comment by msavin** [comment]
Hey folks - did not see these here! They should be fixed. To update, remove and re-add your Meteor Toys packages.
